# Generated by Django 6.0.3 on 2026-04-06 13:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('team_lead', 'Team Lead'), ('hr', 'HR')], default='employee', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('team_lead', models.ForeignKey(blank=True, limit_choices_to={'role': 'team_lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g. Q1 2025, Annual 2025', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_lead', 'Awaiting Team Lead Review'), ('pending_hr', 'Awaiting HR Review'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('self_summary', models.TextField(help_text='Summarise your performance this period.', verbose_name='Overall Summary')),
                ('achievements', models.TextField(help_text='List your major accomplishments.', verbose_name='Key Achievements')),
                ('challenges', models.TextField(help_text='Describe obstacles you encountered and how you handled them.', verbose_name='Challenges Faced')),
                ('goals_next_period', models.TextField(help_text='What do you aim to achieve next period?', verbose_name='Goals for Next Period')),
                ('training_needs', models.TextField(blank=True, help_text="Any skills or training you'd like to pursue.", verbose_name='Training & Development Needs')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Additional Comments')),
                ('lead_comment', models.TextField(blank=True, verbose_name='Team Lead Comments')),
                ('lead_rating', models.IntegerField(blank=True, choices=[(1, '1 – Needs Improvement'), (2, '2 – Below Expectations'), (3, '3 – Meets Expectations'), (4, '4 – Exceeds Expectations'), (5, '5 – Outstanding')], null=True, verbose_name='Overall Rating')),
                ('hr_comment', models.TextField(blank=True, verbose_name='HR Comments')),
                ('hr_decision', models.CharField(blank=True, max_length=100, verbose_name='HR Decision / Outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_to_lead_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_to_hr_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_hr', models.ForeignKey(blank=True, limit_choices_to={'role': 'hr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_lead', models.ForeignKey(blank=True, limit_choices_to={'role': 'team_lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
