# Generated by Django 6.0.4 on 2026-04-14 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='employee_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='employee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='achievements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='challenges',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'employee'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='goals_next_period',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='hr_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='hr_decision',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='lead_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='lead_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Needs Improvement'), (2, '2 - Below Expectations'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Outstanding')], null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='period',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='self_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_lead', 'Awaiting Team Lead Review'), ('pending_hr', 'Awaiting HR Review'), ('reviewed', 'Reviewed')], default='pending_lead', max_length=20),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='training_needs',
            field=models.TextField(blank=True),
        ),
    ]
