# Generated by Django 6.0.4 on 2026-05-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_appraisal_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='goals_next_period',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='self_summary',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='training_needs',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='communication',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='initiative',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='job_knowledge',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='meeting_deadlines',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='professionalism',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='punctuality',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='quality_of_work',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='teamwork',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True),
        ),
    ]
