# Generated by Django 6.0.4 on 2026-05-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_remove_appraisal_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='job_knowledge',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='meeting_deadlines',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='professionalism',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='punctuality',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='quality_of_work',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='teamwork',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_adherence',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Adherence to Company Rules'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_communication',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Communication Skills'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_deadlines',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Meeting Deadlines'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_initiative',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Initiative & Creativity'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_problem_solving',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Problem Solving'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_professionalism',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Professionalism'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_punctuality',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Punctuality & Attendance'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_quality',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Quality of Work'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='score_teamwork',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Good'), (3, '3 - Average'), (2, '2 - Below Average'), (1, '1 - Poor')], null=True, verbose_name='Teamwork & Collaboration'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='lead_rating',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Outstanding'), (4, '4 - Exceeds Expectations'), (3, '3 - Meets Expectations'), (2, '2 - Below Expectations'), (1, '1 - Needs Improvement')], null=True),
        ),
    ]
